import{S as l,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const u="43257853-194068c59ee252fa44b7d008e";function d(s){const o=`https://pixabay.com/api/?key=${u}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>e.hits).catch(e=>(console.error("Error fetching images:",e),[]))}function f(){const s=document.querySelector(".gallery");s.innerHTML=""}function p(s){const o=document.querySelector(".gallery"),e=s.map(n=>`<li class="card">
    <a href="${n.largeImageURL}" data-lightbox="gallery-item">
      <img class="contentCard" src="${n.webformatURL}" alt="${n.tags}">
    </a>
    <div class="imgCard">
      <p><b>Likes:</b> ${n.likes}</p>
      <p><b>Views:</b> ${n.views}</p>
      <p><b>Comments:</b> ${n.comments}</p>
      <p><b>Downloads:</b> ${n.downloads}</p>
    </div></li>
  `).join("");o.insertAdjacentHTML("beforeend",e)}const m=new l(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.getElementById("search-form"),y=document.getElementById("search-input"),c=document.querySelector(".loader");h.addEventListener("submit",s=>{s.preventDefault();const o=y.value.trim();if(!o){a.error({position:"topRight",title:"Error",message:"Please enter a keyword for search."});return}c.style.display="block",f(),d(o).then(e=>{e.length===0?a.info({position:"topRight",title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(p(e),m.refresh())}).catch(e=>{console.error("Error fetching images:",e),a.error({position:"topRight",title:"Error",message:"An error occurred while fetching images. Please try again later."})}).finally(()=>{c.style.display="none"})});
//# sourceMappingURL=commonHelpers.js.map
